### ISSUE TITLE
Unable to transfer from mobile to PC(Windows)

### ISSUE THREAD

**Issue by mouryadwarapudi** [cyrildiagne/ar-cptext#2]

**Comment by mouryadwarapudi** [comment]
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at execute (D:\New folder\ar-cptext-master\desktop\node_modules\node-osascript\lib\index.js:61:11)
    at Object.execute (D:\New folder\ar-cptext-master\desktop\node_modules\node-osascript\lib\index.js:69:10)
    at Object.<anonymous> (D:\New folder\ar-cptext-master\desktop\main.js:28:11)
Emitted 'error' event on Socket instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at internal/streams/destroy.js:50:7
    at Socket._destroy (net.js:679:5)
    at Socket.destroy (internal/streams/destroy.js:38:8)
    at afterWriteDispatched (internal/stream_base_commons.js:154:17)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}

**Comment by mouryadwarapudi** [comment]
I think i came closer.

issue:

> ar-cptext-proto@1.0.0 start D:\New folder\ar-cptext-master\desktop
> electron .


Listening at http://localhost:3000
paste
ignore paste

==
After that it automatically app closes
