### ISSUE TITLE
App threw an error during load

### ISSUE THREAD

**Issue by cr-trojan23** [cyrildiagne/ar-cptext#9]
`npm start` with all the dependencies installed failed with this error:

```
> ar-cptext-proto@1.0.0 start /home/miyoko/Downloads/ar-cptext/desktop
> electron .

App threw an error during load
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:150:25)
    at writeGeneric (internal/stream_base_commons.js:141:3)
    at Socket._writeGeneric (net.js:770:11)
    at Socket._write (net.js:782:8)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Socket.Writable.write (_stream_writable.js:305:11)
    at execute (/home/miyoko/Downloads/ar-cptext/desktop/node_modules/node-osascript/lib/index.js:61:11)
    at Object.execute (/home/miyoko/Downloads/ar-cptext/desktop/node_modules/node-osascript/lib/index.js:69:10)
    at Object.<anonymous> (/home/miyoko/Downloads/ar-cptext/desktop/main.js:28:11)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:150:25)
    at writeGeneric (internal/stream_base_commons.js:141:3)
    at Socket._writeGeneric (net.js:770:11)
    at Socket._write (net.js:782:8)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Socket.Writable.write (_stream_writable.js:305:11)
    at execute (/home/miyoko/Downloads/ar-cptext/desktop/node_modules/node-osascript/lib/index.js:61:11)
    at Object.execute (/home/miyoko/Downloads/ar-cptext/desktop/node_modules/node-osascript/lib/index.js:69:10)
    at Object.<anonymous> (/home/miyoko/Downloads/ar-cptext/desktop/main.js:28:11)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: spawn osascript ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by vishaldhull09** [comment]
Hi i am also getting same error
any idea how to resolve it ?

**Comment by cr-trojan23** [comment]
> Hi i am also getting same error
> any idea how to resolve it ?

No, I didn't find any way to resolve

**Comment by Janarthanans07** [comment]
I also having same issue. I tried a lot but, I can't find any solution.
